name: CI
on:
  push:
    branches:
      - main
jobs:
  build:
    name: test
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node: [ '16', '18', '20.4' ]
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node  }}
      - run: npm install
      - run: npm run test && SYNC=true npm run test
